Add guidelines for Contributing to the slackbot repo
devcongress/slackbot pull request #28
Opened 2016-11-02 13:20 UTC by JeanHuit

This is far from final or perfect.

**Main Points** 
- How can I contribute. 
- Submitting Bug reports
- Submitting Issues
- Submitting Pull Requests
- Style Guides

2016-11-03 06:41 UTC, yawboakye requested changes
Good work @JeanHuit. Please see the comments below.

2016-11-03 06:41 UTC, yawboakye commented on CONTRIBUTING.md
> +```
@JeanHuit Good job listing key requirements for making a contribution. What I'm not sure of whether a block of code is the best display for the requirements. In my opinion we can go with normally formatted text, in a list. What do you think?

2016-11-03 06:41 UTC, yawboakye commented on CONTRIBUTING.md
> +Bugs are tracked as [GitHub issues](https://guides.github.com/features/issues/). After you've determined which repository your bug is related to, create an issue on that repository and provide the fo
Can we make this statement more about this particular project? For example, it could be rewritten to instead say:

Bugs are tracked as [GitHub issues](https://guides.github.com/features/issues/). When you identify a bug, please create an issue [here](https://github.com/devcongress/slackbot/issues) and provide the following information in the following template.

2016-11-03 06:41 UTC, yawboakye commented on CONTRIBUTING.md
> +**Botkit version:** [Enter Botkit version here]
A regular user might not know what Botkit version our bot uses. Is it possible to make this optional? It will make sense to contributors who contribute code than contributors who point out some of the bot's bad behavior. I think we should mark it and other information such as OS and installed packages as optional before non-code contributors don't report the bugs they see.

2016-11-03 06:41 UTC, yawboakye commented on CONTRIBUTING.md
> +###General Code
@oddoye-david and @silentworks please advise.

2016-11-03 06:41 UTC, yawboakye commented on CONTRIBUTING.md
> +* Follow the JavaScript coding style with details from `.jscsrc` and `.editorconfig` files and use necessary plugins for your text editor.
`.jscsrc` and `.editorconfig` are missing from the PR :stuck_out_tongue: Since they don't exist already I suggest to add them to this PR.

2016-11-03 09:16 UTC, oddoye-david commented on CONTRIBUTING.md
> +###General Code
Documentation where necessary should come as changes to `README.md`. JSDoc for sure. PRs i feel should come from the `develop` branch. Thoughts @silentworks ?

2016-11-03 17:05 UTC, JeanHuit commented on CONTRIBUTING.md
> +Bugs are tracked as [GitHub issues](https://guides.github.com/features/issues/). After you've determined which repository your bug is related to, create an issue on that repository and provide the fo
@yawboakye  this makes sense.

2016-11-03 17:21 UTC, JeanHuit commented on CONTRIBUTING.md
> +**Botkit version:** [Enter Botkit version here]
seen and understood.

2016-11-05 07:16 UTC, JeanHuit commented on CONTRIBUTING.md
> +* Follow the JavaScript coding style with details from `.jscsrc` and `.editorconfig` files and use necessary plugins for your text editor.
@yawboakye  I will add a default `.jscsrc` will all the bells and whistles turned on. See if they make sense  and if they fit the pattern already used.

2016-11-05 07:20 UTC, silentworks commented on CONTRIBUTING.md
> +	* This is usually the master branch.
This should be a fork of the `develop` branch, master is likely the release branch most of the times, so won't be the most up to date of code currently being developed.

2016-11-05 07:22 UTC, silentworks commented on CONTRIBUTING.md
> +	* This is usually the master branch.
This should be a fork of the `develop` branch, master is likely the release branch most of the times, so won't be the most up to date of code currently being developed.

2016-11-05 16:41 UTC, JeanHuit commented on CONTRIBUTING.md
> +	* This is usually the master branch.
@silentworks  Seen. I think thats this particular case. I was of the assumption the master branch has all the agreed upon and up to date functioning commits.

2016-11-06 11:00 UTC, tonymobster commented on CONTRIBUTING.md
> +* Follow the JavaScript coding style with details from `.jscsrc` and `.editorconfig` files and use necessary plugins for your text editor.
I'm curious what the difference is between eslint and jscs? I thought I saw a .eslintrc in @yawboakye PR

2016-11-07 08:24 UTC, silentworks commented on CONTRIBUTING.md
> +	* This is usually the master branch.
@JeanHuit `master` branch will be the current stable release, but `develop` branch would have the most up to date code.

2016-12-12 18:39 UTC, merged